POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "admin",
    "password": "admin",
    "email": "jakub213x@gmail.com"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

GET http://localhost:3000/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkphY2VrIiwicGFzc3dvcmQiOiJEemlhZGVrMTIzIiwiaWF0IjoxNzQzMjQ4MDkwLCJleHAiOjE3NDMyNTE2OTB9.MVqvPPDoP-v2d2kgJZbpcP6NsT6ihcUTqkFFYZRtvCo


###

GET http://localhost:3000/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IktheWxlIiwicGFzc3dvcmQiOiJCYWJjaWExMjMiLCJpYXQiOjE3NDMyNDgxODQsImV4cCI6MTc0MzI1MTc4NH0.0uqXmtJPSOtnS8lLM7I7eKX-T3zVADIyLNkYHT0-R9U


