GET http://localhost:5000/chart/completed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoyLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJqYWt1YjIxM3hAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkdW9QNmtJR1M2YmpGTndFQkNwZVFMT1lEQUNVTW0wdWRZaEhPQlNSb0w2b0NmZWJDOG1PUnEiLCJpYXQiOjE3NDQ1NDE1NzgsImV4cCI6MTc0NDU0NTE3OH0.MQ_Z6F8QyyfZwXq335o9HNC9wFCacG9R2Ksk_9MW1yg

###
GET http://localhost:5000/chart/weekly
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoyLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJqYWt1YjIxM3hAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkdW9QNmtJR1M2YmpGTndFQkNwZVFMT1lEQUNVTW0wdWRZaEhPQlNSb0w2b0NmZWJDOG1PUnEiLCJpYXQiOjE3NDQ1NDE3NjIsImV4cCI6MTc0NDU0NTM2Mn0.ZWDBjgDtaT39k1oorAnmRfpOvJAEmdTV5QnQev5SDtg

###
GET http://localhost:5000/chart/monthly
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoyLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJqYWt1YjIxM3hAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkdW9QNmtJR1M2YmpGTndFQkNwZVFMT1lEQUNVTW0wdWRZaEhPQlNSb0w2b0NmZWJDOG1PUnEiLCJpYXQiOjE3NDQ1NDE3NjIsImV4cCI6MTc0NDU0NTM2Mn0.ZWDBjgDtaT39k1oorAnmRfpOvJAEmdTV5QnQev5SDtg

