GET http://localhost:5000/task
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoyLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJqYWt1YjIxM3hAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkdW9QNmtJR1M2YmpGTndFQkNwZVFMT1lEQUNVTW0wdWRZaEhPQlNSb0w2b0NmZWJDOG1PUnEiLCJpYXQiOjE3NDQ2MzU4NjksImV4cCI6MTc0NDYzOTQ2OX0.uNOu4Ce4HVFi6cmMlINLRGxhOzRm1vw2y9gte6e792s
###

GET http://localhost:5000/task/36
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoyLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJqYWt1YjIxM3hAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkdW9QNmtJR1M2YmpGTndFQkNwZVFMT1lEQUNVTW0wdWRZaEhPQlNSb0w2b0NmZWJDOG1PUnEiLCJpYXQiOjE3NDQ2MzU4NjksImV4cCI6MTc0NDYzOTQ2OX0.uNOu4Ce4HVFi6cmMlINLRGxhOzRm1vw2y9gte6e792s
### 

POST http://localhost:5000/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoyLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJqYWt1YjIxM3hAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkdW9QNmtJR1M2YmpGTndFQkNwZVFMT1lEQUNVTW0wdWRZaEhPQlNSb0w2b0NmZWJDOG1PUnEiLCJpYXQiOjE3NDQ2MzU4NjksImV4cCI6MTc0NDYzOTQ2OX0.uNOu4Ce4HVFi6cmMlINLRGxhOzRm1vw2y9gte6e792s

{
    "name": "Bojowe zadanie"
}
###

PUT http://localhost:5000/task/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoyLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJqYWt1YjIxM3hAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkdW9QNmtJR1M2YmpGTndFQkNwZVFMT1lEQUNVTW0wdWRZaEhPQlNSb0w2b0NmZWJDOG1PUnEiLCJpYXQiOjE3NDQ2MzU4NjksImV4cCI6MTc0NDYzOTQ2OX0.uNOu4Ce4HVFi6cmMlINLRGxhOzRm1vw2y9gte6e792s

{
    "name": "Cokolwiek"
}
###

DELETE http://localhost:5000/task/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoyLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJqYWt1YjIxM3hAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkdW9QNmtJR1M2YmpGTndFQkNwZVFMT1lEQUNVTW0wdWRZaEhPQlNSb0w2b0NmZWJDOG1PUnEiLCJpYXQiOjE3NDQ2MzU4NjksImV4cCI6MTc0NDYzOTQ2OX0.uNOu4Ce4HVFi6cmMlINLRGxhOzRm1vw2y9gte6e792s

